### ISSUE TITLE
Number is scientific notation can be followed by a sign

### ISSUE THREAD

**Issue by eddyw** [csstools/parser#4]
👋  nice job with the tokenizer

# Description

From specs: https://drafts.csswg.org/css-syntax/#consume-number
> If the next 2 or 3 input code points are U+0045 LATIN CAPITAL LETTER E (E) or U+0065 LATIN SMALL LETTER E (e), optionally followed by U+002D HYPHEN-MINUS (-) or U+002B PLUS SIGN (+), followed by a digit, then:
> 1. Consume them.
> 2. Append them to repr.
> 3. Set type to "number".
> 4. While the next input code point is a digit, consume it and append it to repr.

The logic looks okay.. but I think you forgot to consume the sign:
https://github.com/csstools/parser/blob/1e59d1b08b6dcfebd0cdd418c1bb06ff69ee62de/src/tokenize/tokenize.js#L618
It should be .. I think:
```javascript
&& isInteger(cssText.charCodeAt(shut + 2))
```
It's `+ 2` because you didn't consume the sign (didn't do `++shut`, so `shut` still points to `e`|`E`). Otherwise the check is always false.

# Steps to reproduce
1. Open https://csstools.github.io/parser/
2. Type
```css
#c {
  border: 1e+1px
}
```
3. see AST displays
<img width="237" alt="Screen Shot 2020-07-30 at 2 04 26 PM" src="https://user-images.githubusercontent.com/1407526/88886676-961d6b00-d26d-11ea-9e17-1302962d531b.png">

# Additional

From specs, `consume number` (called by `consume numeric token`) should return `6. convert repl to number` which is described here: https://drafts.csswg.org/css-syntax-3/#convert-string-to-number
Since the tokenizer is written in JS, you can pretty much ignore it all and just do `parseFloat(this.value)`. Could `CSSNumber` return, for example:

```javascript
CSSNumber {
   value: "12e+1",
   number: 120, // Result of parseFloat(value)
   unit: "px",
}
```

Anyways, this last thing is just a suggestion and I'm not sure how `parseFloat` would affect performance 😅

**Comment by jonathantneal** [comment]
### About the tokenizing logic

You wrote:

> The logic looks okay.. 

Thank you! I desire the logic to look like the best possible implementation, especially within the tokenizer. If you have seen it done in a more performant or clear way (_or a way that you believe it is worth any trade-offs_), I would be grateful if you would direct me to it. 🙇

I have more broad comments to make about this.

This project may seem to diverge from the css-syntax specification to preserve ”lossless” tokens like comments or non-line-feed characters, and to preserve fragments of productions like skippable tokens or unknown groups. These lossless bits are discarded in the official specification. They are preserved in this project so that input and output strings may be 1:1. The specification appears to condone this, at least as I interpret [Section 10](https://drafts.csswg.org/css-syntax/#serialization):

> The tokenizer described in this specification does not produce tokens for comments, or otherwise preserve them in any way. Implementations may preserve the contents of comments and their location in the token stream. If they do, this preserved information must have no effect on the parsing step.

This gets more tricky when the specification seems to conflict with another specification. I am dealing with at least 2 instances of this.

1. The [nesting selector in the CSS Nesting specification](https://drafts.csswg.org/css-nesting/) seems incompatible with the [allowable list of declarations in the CSS Syntax specification](https://drafts.csswg.org/css-syntax-3/#consume-list-of-declarations). I will document this project’s algorithm, which attempts to honor both specifications.

2. The [strictly interpreted `important` flag in the CSS Syntax specification](https://drafts.csswg.org/css-syntax-3/#declaration) suspiciously contrasts with the [loose `priority` naming used in the CSS Object Model specification](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-getpropertypriority). Furthermore, an editor of the css-syntax wrote that `priority` is [intentionally open-ended](https://github.com/w3c/css-houdini-drafts/issues/922#issuecomment-515199449). I am documenting this project’s algorithm ([here](https://github.com/csstools/parser/tree/jn.documentation/src/consumers#cssdeclaration)), which attempts to honor both the specification and the written intention.

### About the number conversion

You wrote:

> Since the tokenizer is written in JS, you can pretty much ignore it all and just do parseFloat(this.value). Could CSSNumber return, for example:

This could be implemented on all CSS Number tokens with an accessor, which I would be interested in adding (as `Number(this.value)`).
